# Generated by Django 4.1.3 on 2022-11-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(db_index=True, related_name='book', to='books.author'),
        ),
    ]
